databases:
  - name: spanish-project
    databaseName: spanish-project
    user: spanish-project
    plan: free

services:
  - type: web
    name: spanish-project
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spanish-project
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
