databases:
  - name: spanish_project_ruby
    databaseName: spanish_project_ruby
    user: spanish_project_ruby_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: spanish_project_ruby
    runtime: ruby
    plan: free
    region: frankfurt
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spanish_project_ruby
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
