name: CI RSpec tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Print DATABASE_URL
        run: echo $DATABASE_URL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Set up database
        env:
          RAILS_ENV: test
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: Run tests
        run: bundle exec rspec
