name: Run RSpec tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: setup databases
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          RAILS_ENV: test
        run: bundle exec db:prepare

      - name: Run tests
        run: |
          bundle exec rspec
